// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// IDirectoryHelper is an autogenerated mock type for the IDirectoryHelper type
type IDirectoryHelper struct {
	mock.Mock
}

// CreateRequiredFolders provides a mock function with given fields: sub
func (_m *IDirectoryHelper) CreateRequiredFolders(sub string) {
	_m.Called(sub)
}
