// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// IDownloader is an autogenerated mock type for the IDownloader type
type IDownloader struct {
	mock.Mock
}

// MakeRequestForReddit provides a mock function with given fields: subreddit, limit
func (_m *IDownloader) MakeRequestForReddit(subreddit string, limit int) {
	_m.Called(subreddit, limit)
}
